### Machine Learning com Python - Regras de associação
#### analise de dados de Mercado/ varejo

# Algoritmo Apriori

In [ ]:
!pip install apyori

Collecting apyori
  Downloading https://files.pythonhosted.org/packages/5e/62/5ffde5c473ea4b033490617ec5caa80d59804875ad3c3c57c0976533a21a/apyori-1.1.2.tar.gz
Building wheels for collected packages: apyori
  Building wheel for apyori (setup.py) ... done
  Created wheel for apyori: filename=apyori-1.1.2-cp37-none-any.whl size=5975 sha256=fc16b1e6377ce23ae787474aa2fa4e7b913cfb0c1dc2296ae352c40b159975c5
  Stored in directory: /root/.cache/pip/wheels/5d/92/bb/474bbadbc8c0062b9eb168f69982a0443263f8ab1711a8cad0
Successfully built apyori
Installing collected packages: apyori
Successfully installed apyori-1.1.2

In [ ]:
import pandas as pd
from apyori import apriori

## Base de dados mercado 1

In [ ]:
base_mercado1 = pd.read_csv('mercado.csv', header = None)
base_mercado1

          0        1         2         3
0     leite  cerveja       pao  manteiga
1      cafe      pao  manteiga       NaN
2      cafe      pao  manteiga       NaN
3     leite     cafe       pao  manteiga
4   cerveja      NaN       NaN       NaN
5  manteiga      NaN       NaN       NaN
6       pao      NaN       NaN       NaN
7    feijao      NaN       NaN       NaN
8     arroz   feijao       NaN       NaN
9     arroz      NaN       NaN       NaN

In [ ]:
base_mercado1.shape

(10, 4)

In [ ]:
transacoes = []
for i in range(len(base_mercado1)):
  #print(i)
  #print(base_mercado1.values[i, 0])
  transacoes.append([str(base_mercado1.values[i, j]) for j in range(base_mercado1.shape[1])])

In [ ]:
transacoes

[['leite', 'cerveja', 'pao', 'manteiga'],
 ['cafe', 'pao', 'manteiga', 'nan'],
 ['cafe', 'pao', 'manteiga', 'nan'],
 ['leite', 'cafe', 'pao', 'manteiga'],
 ['cerveja', 'nan', 'nan', 'nan'],
 ['manteiga', 'nan', 'nan', 'nan'],
 ['pao', 'nan', 'nan', 'nan'],
 ['feijao', 'nan', 'nan', 'nan'],
 ['arroz', 'feijao', 'nan', 'nan'],
 ['arroz', 'nan', 'nan', 'nan']]

In [ ]:
type(transacoes)

list

In [ ]:
regras = apriori(transacoes, min_support = 0.3, min_confidence = 0.8, min_lift = 2)
resultados = list(regras)

In [ ]:
resultados

[RelationRecord(items=frozenset({'cafe', 'manteiga'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0)]),
 RelationRecord(items=frozenset({'cafe', 'pao'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0)]),
 RelationRecord(items=frozenset({'cafe', 'manteiga', 'pao'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'manteiga', 'pao'}), confidence=1.0, lift=2.5), OrderedStatistic(items_base=frozenset({'cafe', 'manteiga'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'cafe', 'pao'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0)])]

In [ ]:
len(resultados)

3

In [ ]:
resultados[2]

RelationRecord(items=frozenset({'cafe', 'manteiga', 'pao'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'manteiga', 'pao'}), confidence=1.0, lift=2.5), OrderedStatistic(items_base=frozenset({'cafe', 'manteiga'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'cafe', 'pao'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0)])

RelationRecord(items=frozenset({'cafe', 'manteiga', 'pao'}), support=0.3, ordered_statistics=[OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'manteiga', 'pao'}), confidence=1.0, lift=2.5), OrderedStatistic(items_base=frozenset({'cafe', 'manteiga'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0), OrderedStatistic(items_base=frozenset({'cafe', 'pao'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0)])

In [ ]:
resultados[2][0]

frozenset({'cafe', 'manteiga', 'pao'})

In [ ]:
resultados[2][1]

0.3

In [ ]:
r = resultados[2][2]
r

[OrderedStatistic(items_base=frozenset({'cafe'}), items_add=frozenset({'manteiga', 'pao'}), confidence=1.0, lift=2.5),
 OrderedStatistic(items_base=frozenset({'cafe', 'manteiga'}), items_add=frozenset({'pao'}), confidence=1.0, lift=2.0),
 OrderedStatistic(items_base=frozenset({'cafe', 'pao'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0)]

In [ ]:
r[2]

OrderedStatistic(items_base=frozenset({'cafe', 'pao'}), items_add=frozenset({'manteiga'}), confidence=1.0, lift=2.0)

In [ ]:
r[2][0]

frozenset({'cafe', 'pao'})

In [ ]:
r[2][1]

frozenset({'manteiga'})

In [ ]:
r[2][2]

1.0

In [ ]:
r[2][3]

2.0

In [ ]:
A = []
B = []
suporte = []
confianca = []
lift = []

for resultado in resultados:
  #print(resultado)
  s = resultado[1]
  #print(s)
  result_rules = resultado[2]
  #print(result_rule)
  for result_rule in result_rules:
    #print(result_rule)
    a = list(result_rule[0])
    b = list(result_rule[1])
    c = result_rule[2]
    l = result_rule[3]
    #print(a, ' - ', b, ' - ', c, ' - ', l)
    A.append(a)
    B.append(b)
    suporte.append(s)
    confianca.append(c)
    lift.append(l)

In [ ]:
A

[['cafe'], ['cafe'], ['cafe'], ['cafe', 'manteiga'], ['cafe', 'pao']]

In [ ]:
B

[['manteiga'], ['pao'], ['manteiga', 'pao'], ['pao'], ['manteiga']]

In [ ]:
s

0.3

In [ ]:
confianca

[1.0, 1.0, 1.0, 1.0, 1.0]

In [ ]:
lift

[2.0, 2.0, 2.5, 2.0, 2.0]

In [ ]:
rules_df = pd.DataFrame({'A': A, 'B': B, 'suporte': suporte, 'confianca': confianca, 'lift': lift})

In [ ]:
rules_df.sort_values(by = 'lift', ascending = False)

                  A                B  suporte  confianca  lift
2            [cafe]  [manteiga, pao]      0.3        1.0   2.5
0            [cafe]       [manteiga]      0.3        1.0   2.0
1            [cafe]            [pao]      0.3        1.0   2.0
3  [cafe, manteiga]            [pao]      0.3        1.0   2.0
4       [cafe, pao]       [manteiga]      0.3        1.0   2.0

## Base de dados mercado 2

In [ ]:
base_mercado2 = pd.read_csv('mercado2.csv', header=None)
base_mercado2

                 0                  1   ...       18         19
0            shrimp            almonds  ...  spinach  olive oil
1           burgers          meatballs  ...      NaN        NaN
2           chutney                NaN  ...      NaN        NaN
3            turkey            avocado  ...      NaN        NaN
4     mineral water               milk  ...      NaN        NaN
...             ...                ...  ...      ...        ...
7496         butter         light mayo  ...      NaN        NaN
7497        burgers  frozen vegetables  ...      NaN        NaN
7498        chicken                NaN  ...      NaN        NaN
7499       escalope          green tea  ...      NaN        NaN
7500           eggs    frozen smoothie  ...      NaN        NaN

[7501 rows x 20 columns]

In [ ]:
base_mercado2.shape

(7501, 20)

In [ ]:
transacoes = []
for i in range(base_mercado2.shape[0]):
  transacoes.append([str(base_mercado2.values[i, j]) for j in range(base_mercado2.shape[1])])

In [ ]:
transacoes

In [ ]:
# Produtos que são vendidos 4 vezes por dia

In [ ]:
4 * 7

28

In [ ]:
28 / 7501

0.0037328356219170776

In [ ]:
regras = apriori(transacoes, min_support = 0.003, min_confidence = 0.2, min_lift = 3)
resultados = list(regras)
len(resultados)

160

In [ ]:
A = []
B = []
suporte = []
confianca = []
lift = []

for resultado in resultados:
  s = resultado[1]
  result_rules = resultado[2]
  for result_rule in result_rules:
    a = list(result_rule[0])
    b = list(result_rule[1])
    c = result_rule[2]
    l = result_rule[3]
    A.append(a)
    B.append(b)
    suporte.append(s)
    confianca.append(c)
    lift.append(l)

In [ ]:
rules_df = pd.DataFrame({'A': A, 'B': B, 'suporte': suporte, 'confianca': confianca, 'lift': lift})
rules_df.sort_values(by = 'confianca', ascending = False)

                                        A  ...      lift
347       [frozen vegetables, soup, milk]  ...  3.218112
353  [frozen vegetables, nan, soup, milk]  ...  3.216312
180       [frozen vegetables, soup, milk]  ...  3.216312
106           [cereals, nan, ground beef]  ...  3.885303
104                [cereals, ground beef]  ...  3.885303
..                                    ...  ...       ...
358           [frozen vegetables, shrimp]  ...  3.348661
371              [nan, ground beef, milk]  ...  3.348661
370                   [ground beef, milk]  ...  3.348661
224                   [ground beef, milk]  ...  3.348661
360      [frozen vegetables, shrimp, nan]  ...  3.348661

[390 rows x 5 columns]

# ECLAT

In [ ]:
!pip install pyECLAT

In [ ]:
base_mercado1 = pd.read_csv('mercado.csv', header = None)
base_mercado1

          0        1         2         3
0     leite  cerveja       pao  manteiga
1      cafe      pao  manteiga       NaN
2      cafe      pao  manteiga       NaN
3     leite     cafe       pao  manteiga
4   cerveja      NaN       NaN       NaN
5  manteiga      NaN       NaN       NaN
6       pao      NaN       NaN       NaN
7    feijao      NaN       NaN       NaN
8     arroz   feijao       NaN       NaN
9     arroz      NaN       NaN       NaN

In [ ]:
from pyECLAT import ECLAT
eclat = ECLAT(data = base_mercado1)

In [ ]:
eclat.df_bin

   cerveja  pao  cafe  feijao  leite  arroz  manteiga
0        1    1     0       0      1      0         1
1        0    1     1       0      0      0         1
2        0    1     1       0      0      0         1
3        0    1     1       0      1      0         1
4        1    0     0       0      0      0         0
5        0    0     0       0      0      0         1
6        0    1     0       0      0      0         0
7        0    0     0       1      0      0         0
8        0    0     0       1      0      1         0
9        0    0     0       0      0      1         0

In [ ]:
eclat.uniq_

[nan, 'cerveja', 'pao', 'cafe', 'feijao', 'leite', 'arroz', 'manteiga']

In [ ]:
indices, suporte = eclat.fit(min_support=0.3, min_combination=1, max_combination=3)

3it [00:00, 110.13it/s]
3it [00:00, 132.27it/s]
1it [00:00, 71.19it/s]

Combination 1 by 1
Combination 2 by 2
Combination 3 by 3

In [ ]:
indices

{'cafe': [1, 2, 3],
 'cafe & manteiga': [1, 2, 3],
 'manteiga': [0, 1, 2, 3, 5],
 'pao': [0, 1, 2, 3, 6],
 'pao & cafe': [1, 2, 3],
 'pao & cafe & manteiga': [1, 2, 3],
 'pao & manteiga': [0, 1, 2, 3]}

In [ ]:
suporte

{'cafe': 0.3,
 'cafe & manteiga': 0.3,
 'manteiga': 0.5,
 'pao': 0.5,
 'pao & cafe': 0.3,
 'pao & cafe & manteiga': 0.3,
 'pao & manteiga': 0.4}